<a href="https://colab.research.google.com/github/sayem088/AI-and-Iot-driven-WtE-research-paper-stat/blob/main/Stoten_paper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
df = pd.read_excel("Urban_Waste_Data.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       359 non-null    object
 1   Gender                     359 non-null    int64
 2   Age                        359 non-null    int64
 3   Education                  359 non-null    int64
 4   Occupation                 339 non-null    float64
 5   HH_Income                  359 non-null    int64
 6   HH_Size                    359 non-null    int64
 7   Expenditure                359 non-null    int64
 8   Duration_Living            359 non-null    int64
 9   House_Type                 351 non-null    float64
 10  Distance_to_Waste_Point    358 non-null    float64
 11  Waste_Gen_Types            359 non-null    int64
 12  Waste_Production           358 non-null    float64
 13  WtE_Tech_Awarness          359 non-null    int64
 14  Feasibility                359 non-null    int64
 15  Personal_Interest          359 non-null    int64
 16  Concerns                   359 non-null    int64
 17  Current_Disposal           358 non-null    float64
 18  Current_Pay                357 non-null    float64
 19  Current_Management         358 non-null    float64
 20  Effectiveness_CWM          358 non-null    float64
 21  Subsidy_Acceptance         358 non-null    float64
 22  Subsidy_Amount             255 non-null    float64
 23  SMART_Disposal_Conception  359 non-null    int64
 24  Willingness_to_Adapt       359 non-null    int64
 25  Willingness_to_Pay         359 non-null    int64
 26  Amount_Willingness_to_pay  262 non-null    float64
 27  WtE_Technology_Preference  335 non-null    float64
 28  Desired_Outcome            358 non-null    float64
dtypes: float64(13), int64(15), object(1)
memory usage: 81.5+ KB

In [14]:
missing = df.isna().mean().sort_values(ascending=False)
missing

Subsidy_Amount               0.289694
Amount_Willingness_to_pay    0.270195
WtE_Technology_Preference    0.066852
Occupation                   0.055710
House_Type                   0.022284
Current_Pay                  0.005571
Current_Disposal             0.002786
Effectiveness_CWM            0.002786
Subsidy_Acceptance           0.002786
Current_Management           0.002786
Distance_to_Waste_Point      0.002786
Waste_Production             0.002786
Desired_Outcome              0.002786
Waste_Gen_Types              0.000000
HH_Size                      0.000000
Expenditure                  0.000000
Duration_Living              0.000000
HH_Income                    0.000000
Gender                       0.000000
Age                          0.000000
Education                    0.000000
Name                         0.000000
Feasibility                  0.000000
Personal_Interest            0.000000
Concerns                     0.000000
WtE_Tech_Awarness            0.000000
SMART_Disposal_Conception    0.000000
Willingness_to_Adapt         0.000000
Willingness_to_Pay           0.000000
dtype: float64

In [15]:
required_columns = [
    "Education",
    "Expenditure",
    "HH_Size",
    "WtE_Tech_Awarness",
    "Feasibility",
    "Personal_Interest",
    "Concerns",
    "Willingness_to_Adapt",
    "Willingness_to_Pay"
]

In [18]:
df = df[required_columns]
df.head()

,Education,Expenditure,HH_Size,WtE_Tech_Awarness,Feasibility,Personal_Interest,Concerns,Willingness_to_Adapt,Willingness_to_Pay
0,5,3,3,1,1,5,1,3,2
1,3,2,1,1,2,4,4,1,1
2,2,3,2,1,3,3,2,2,2
3,3,2,3,2,4,3,4,3,2
4,1,2,2,1,2,2,4,2,2

In [19]:
N = len(df)

In [20]:
aware_pct = (df["WtE_Tech_Awarness"] == 1).mean() * 100
aware_pct

np.float64(72.70194986072424)

In [21]:
adopt_yes_pct = (df["Willingness_to_Adapt"] == 1).mean() * 100
adopt_potential_pct = df["Willingness_to_Adapt"].isin([1, 3]).mean() * 100

adopt_yes_pct, adopt_potential_pct

(np.float64(42.89693593314763), np.float64(67.68802228412257))

In [22]:
wtp_pct = (df["Willingness_to_Pay"] == 1).mean() * 100
wtp_pct

np.float64(56.26740947075209)

In [25]:
positive_perception_pct = df["Feasibility"].isin([1, 2]).mean() * 100
positive_perception_pct

np.float64(75.4874651810585)